# Generated by Django 5.1.7 on 2025-05-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('manager', 'manager')], default='user', max_length=7, verbose_name='Роль пользователя'),
        ),
    ]
