# Generated by Django 5.1.7 on 2025-06-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('manager', 'manager'), ('admin', 'admin')], default='user', max_length=7, verbose_name='Роль пользователя'),
        ),
    ]
