# Generated by Django 5.2 on 2025-10-09 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название покрытия')),
                ('slug', models.SlugField(unique=True, verbose_name='Сылка')),
            ],
            options={
                'verbose_name': 'Покрытие',
                'verbose_name_plural': 'Покрытия',
            },
        ),
        migrations.CreateModel(
            name='IndoorSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=10, verbose_name='Признак крытое/нет')),
                ('slug', models.SlugField(unique=True, verbose_name='Сылка/крыт')),
            ],
            options={
                'verbose_name': 'Признак крытое/нет',
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=50, verbose_name='Адрес')),
                ('phone_number', models.CharField(default=None, max_length=12, verbose_name='телефон')),
                ('opening_hours', models.CharField(default=None, max_length=12, verbose_name='время работы')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Картинка поля')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание поля')),
                ('indoor', models.BooleanField(default=True, verbose_name='Открытое')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена за час')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='field_rental.cover', verbose_name='Покрытие')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец поля')),
                ('indoorsign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='field_rental.indoorsign', verbose_name='Признак крытое/нет')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата игры')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('canceled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=100, verbose_name='Статус бронирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания брони')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления брони')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='field_rental.fields', verbose_name='Футбольное поле')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
