# Generated by Django 5.2 on 2025-10-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fields',
            name='indoor',
        ),
    ]
