# Generated by Django 5.1.7 on 2025-03-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена за час'),
        ),
    ]
