# Generated by Django 5.2 on 2025-06-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_rental', '0003_fields_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='indoor',
            field=models.CharField(choices=[('Открытое', 'Открытое'), ('Крытое', 'Крытое')], max_length=10, null=True, verbose_name='Открытое'),
        ),
    ]
