# Generated by Django 5.2.3 on 2025-06-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_rental', '0004_fields_indoor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='indoor',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Открытое'),
        ),
    ]
