# Generated by Django 5.1.7 on 2025-06-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_rental', '0005_alter_fields_indoor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='indoor',
            field=models.BooleanField(default=True, verbose_name='Открытое'),
        ),
    ]
