# Generated by Django 5.1.7 on 2025-07-28 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_rental', '0007_booking_delete_pays_delete_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 28, 15, 17, 18, 144311, tzinfo=datetime.timezone.utc), verbose_name='Дата игры'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
    ]
