# Generated by Django 5.2.3 on 2025-08-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_rental', '0008_booking_date_alter_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['start_time'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='end_time_after_start_time',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_slot',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Ожидает подтверждения', 'pending'), ('confirmed', 'Подтверждено'), ('canceled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=100, verbose_name='Статус бронирования'),
        ),
    ]
