# Generated by Django 5.1.7 on 2025-09-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_rental', '0009_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AddField(
            model_name='fields',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание поля'),
        ),
        migrations.AddField(
            model_name='fields',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Картинка поля'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('canceled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=100, verbose_name='Статус бронирования'),
        ),
    ]
