# Generated by Django 5.1.7 on 2025-10-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_rental', '0010_alter_booking_options_alter_booking_status'),
        ('field_rental', '0010_alter_booking_options_fields_description_fields_img_and_more'),
    ]

    operations = [
    ]
