# Generated by Django 5.1.7 on 2025-10-06 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_rental', '0011_merge_20251006_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название покрытия')),
                ('slug', models.SlugField(unique=True, verbose_name='Сылка')),
            ],
            options={
                'verbose_name': 'Покрытие',
                'verbose_name_plural': 'Покрытия',
            },
        ),
        migrations.AlterField(
            model_name='fields',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='field_rental.cover', verbose_name='Покрытие'),
        ),
    ]
